routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Default route
Route::redirect('/', '/events');

// List of events
Route::resource('events', 'EventController');

// Get organisers select drop down via Ajax call
Route::post('/events/getorganisers', 'EventController@getOrganisers');

// Retrieve distance and duration from origin to destination
Route::post('/maps/getinfo', 'MapsController@getInfo');

app/Event.php
<?php

namespace App;

use App\Http\Controllers\MapsController;
use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $primaryKey = 'event_id';

    protected $fillable = [
        'name',
        'description',
        'event_type_id',
        'organisers',
        'participants',
        'date',
        'time',
        'location',
        'venue_distance',
        'venue_travel_time'
    ];

    /**
     * Retrieve all saved events
     * Overwrite events, participants and organisers ids with name in the fetched array
     *
     * @return array
     */
    public static function getEventsForView()
    {
        $events = Event::all()->toArray();

        foreach ($events as &$event) {
            // Overwrite event ids with events names
            $event['event_type'] = EventType::where('event_type_id', $event['event_type_id'])->first()->event_type_name;

            // Overwrite participant ids with participant names
            $participants = json_decode($event['participants']);
            foreach ($participants as &$participant_id) {
                $participant_id = ParticipantType::where('participant_type_id', $participant_id)->first()->participant_type_name;
            }
            $event['participants'] = implode(',', $participants);

            // If organisers were assigned
            if ($event['organisers'] != "null") {
                // Overwrite organiser ids with organisers names
                $organisers = json_decode($event['organisers']);
                foreach ($organisers as &$organiser_id) {
                    $organiser_id = Organiser::where('organiser_type_id', $organiser_id)->first()->organiser_name;
                }
                $event['organisers'] = implode(',', $organisers);
            }
        }

        return $events;
    }

    /**
     * If distance and time sent via form submit use them
     * otherwise send new request to Google maps
     *
     * @param $request
     * @return array
     */
    public static function getDistanceAndTime($request)
    {
        $response = array();

        // If distance and time hidden input fields were not set on form submission
        // Get duration and time from google
        if ($request->get('distance') === null && $request->get('time') === null) {
            $maps = new MapsController();
            $request->destination = $request->get('location');
            $response = $maps->getInfo($request);
        } else {
            $response['distance'] = $request->get('distance');
            $response['time'] = $request->get('time');
        }

        return $response;
    }
}

app/EventType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EventType extends Model
{
    protected $primaryKey = 'event_type_id';
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\EventType;
use App\Organiser;
use App\ParticipantType;
use Illuminate\Http\Request;
use App\Event;


class EventController extends Controller
{
    /**
     * Display a listing of the events.test
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // All events
        $events = Event::getEventsForView();

        return view('events.index', compact('events'));
    }

    /**
     * Show the form for creating a new event.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = array();

        // Event types
        $data['eventTypes'] = EventType::all()->toArray();

        // Event organisers
        $data['organisers'] = Organiser::all()->toArray();

        // Event participant types
        $data['participantTypes'] = ParticipantType::all()->toArray();

        return view('events.create', ["eventTypes" => $data['eventTypes'], "organisers" => $data['organisers'],
            "participantTypes" => $data['participantTypes']]);
    }

    /**
     * Store a newly created event in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Form validation
        $request->validate(
            [
            'name' => 'required',
            'description' => 'required',
            'event-type' => 'required',
            'event-date' => 'required',
            'event-time' => 'required',
            'location' => 'required',
            'participants' => 'required',
            ]
        );

        // Get the distance and travelling time between school and venue
        $response = Event::getDistanceAndTime($request);

        // Create new event on successful validation
        $event = new Event(
            [
            'name' => $request->get('name'),
            'description' => $request->get('description'),
            'event_type_id' => $request->get('event-type'),
            'organisers' => json_encode($request->get('organisers')),
            'participants' => json_encode($request->get('participants')),
            'date' => $request->get('event-date'),
            'time' => $request->get('event-time'),
            'location' => $request->get('location'),
            'venue_distance' => isset($response['distance']) ? $response['distance'] : null,
            'venue_travel_time' => isset($response['time']) ? $response['time'] : null,
            ]
        );
        $event->save();

        return redirect('/events')->with('success', 'Event saved!');
    }

    /**
     * Display the specified event.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified event.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // Get specific event by id
        $event = Event::find($id);

        // JSON decode participants and organisers
        $event->participants = json_decode($event->participants);
        $event->organisers = json_decode($event->organisers);

        $data = array();

        // All event types
        $data['eventTypes'] = EventType::all()->toArray();

        // Get organisers based on event's type
        $data['organisers'] = Organiser::find(['organiser_type_id' => $event->event_type_id])->toArray();

        // All participant types
        $data['participantTypes'] = ParticipantType::all()->toArray();

        return view('events.edit', ["event" => $event, "eventTypes" => $data['eventTypes'], "organisers" => $data['organisers'], "participantTypes" => $data['participantTypes']]);
    }

    /**
     * Update the specified event in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int                      $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Form validation
        $request->validate(
            [
            'name' => 'required',
            'description' => 'required',
            'event-type' => 'required',
            'event-date' => 'required',
            'event-time' => 'required',
            'location' => 'required',
            'participants' => 'required',
            ]
        );

        // Get the distance and travelling time between school and venue
        $response = Event::getDistanceAndTime($request);

        $date = $request->get('event-date');

        // Convert cached date values from form's date field (local computer)
        if (isset($date)) {
            $date = strtr($request->get('event-date'), '/', '-');
        }

        // Update the event
        $event = Event::find($id);
        $event->name = $request->get('name');
        $event->description = $request->get('description');
        $event->event_type_id = $request->get('event-type');
        $event->organisers = json_encode($request->get('organisers'));
        $event->participants = json_encode($request->get('participants'));
        $event->date = $date;
        $event->time = $request->get('event-time');
        $event->location = $request->get('location');
        $event->venue_distance = isset($response['distance']) ? $response['distance'] : null;
        $event->venue_travel_time = isset($response['time']) ? $response['time'] : null;
        $event->save();

        return redirect('/events')->with('success', 'Event updated!');
    }

    /**
     * Remove the specified event from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Get event object
        $event = Event::find($id);

        // Delete the event
        $event->delete();

        return redirect('/events')->with('success', 'Event deleted!');
    }

    /**
     * Ajax request for the organiser based on event type
     *
     * @param  Request $request
     * @return array
     */
    public function getOrganisers(Request $request)
    {
        // Organisers for the event type selected
        $organisers = Organiser::where('organiser_type_id', $request->event_type_id)->get();

        return $organisers;
    }
}

resources/views/events/create.blade.php
@extends('base')

@section('main')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h1 class="display-3">Add an event</h1>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br/>
                @endif
                <form id="form" method="post" action="{{ route('events.store') }}">
                    @csrf
                    <div class="form-group">
                        <label for="name">Name:</label>
                        <input type="text" class="form-control" name="name" value="{{ old('name') }}"/>
                    </div>

                    <div class="form-group">
                        <label for="description">Description:</label>
                        <input type="text" name="description" class="form-control" value="{{ old('description') }}"/>
                    </div>

                    <div class="form-group">
                        <label for="events">Event Type:</label>
                        <div>
                            <select id="events" name="event-type" class="required form-control">
                                <option value="">Select</option>
                                @foreach($eventTypes as $item)
                                    <option {{ (\Illuminate\Support\Facades\Input::old("event-type") == $item['event_type_id'] ? "selected":"") }} value="{{$item['event_type_id']}}">{{$item['event_type_name']}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div id="organiser-container" style="display: none" class="form-group"></div>

                    <div class="form-group">
                        <label for="basic">Participants:</label>
                        <select name="participants[]" id="participants-id" multiple="multiple" class="form-control">
                            @foreach($participantTypes as $item)
                                <option value="{{$item['participant_type_id']}}">{{$item['participant_type_name']}}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="basic">Date:</label>
                        <input type="text" class="form-control" name="event-date" id="datefield"
                               value="{{ old('event-date') }}">
                    </div>

                    <div class="form-group">
                        <label for="basic">Time:</label>
                        <input type="time" class="form-control" name="event-time" value="{{ old('event-time') }}">
                    </div>

                    <div class="form-group">
                        <label for="basic">Location:</label>
                        <input type="text" class="form-control" name="location" id="location"
                               value="{{ old('location') }}">
                        <input type="hidden" value="" id="distance" name="distance">
                        <input type="hidden" value="" id="time" name="time">
                        <div id="info-display"></div>
                    </div>
                    <div class="form-group">
                        <button type="button" class="btn btn-info" id="information">Check Distance and Time</button>
                    </div>

                    <button type="submit" id="submit-button" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/events/edit.blade.php
@extends('base')
@section('main')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h1 class="display-3">Update an event</h1>

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                <br />
            @endif
            <form id="form" method="post" action="{{ route('events.update', $event->event_id) }}">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" name="name" value="{{ $event->name }}"/>
                </div>

                <div class="form-group">
                    <label for="description">Description:</label>
                    <input type="text" name="description" class="form-control" value="{{ $event->description }}"/>
                </div>

                <div class="form-group">
                    <label for="events">Event Type:</label>
                    <div>
                        <select id="events" name="event-type" class="required form-control">
                            <option value="">Select</option>
                            @foreach($eventTypes as $item)
                                <option {{ $event->event_type_id == $item['event_type_id'] ? "selected":"" }} value="{{$item['event_type_id']}}">{{$item['event_type_name']}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

{{--                @isset($event->organisers)--}}
                    <div id="organiser-container" style="display: block" class="form-group">
                        <label for="basic">Organisers:</label>
                        <select name="organisers[]" id="organisers-id" multiple="multiple" class="form-control">
                            @foreach($organisers as $item)
                                @if($event->organisers != null)
                                    @if(in_array($item['organiser_id'], $event->organisers))
                                        <option selected value="{{$item['organiser_id']}}">{{$item['organiser_name']}}</option>
                                    @endif
                                @else
                                    <option value="{{$item['organiser_id']}}">{{$item['organiser_name']}}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
{{--                @endisset--}}

                @isset($event->participants)
                    <div class="form-group">
                        <label for="basic">Participants:</label>
                        <select name="participants[]" id="participants-id" multiple="multiple" class="form-control">
                            @foreach($participantTypes as $item)
                                @if(in_array($item['participant_type_id'], $event->participants))
                                    <option selected value="{{$item['participant_type_id']}}">{{$item['participant_type_name']}}</option>
                                @else
                                    <option value="{{$item['participant_type_id']}}">{{$item['participant_type_name']}}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                @endisset

                <div class="form-group">
                    <label for="basic">Date:</label>
                    <input type="text" class="form-control" name="event-date" id="datefield" value="{{ $event->date }}">
                </div>

                <div class="form-group">
                    <label for="basic">Time:</label>
                    <input type="time" class="form-control" name="event-time" value="{{ $event->time }}">
                </div>

                <div class="form-group">
                    <label for="basic">Location:</label>
                    <input type="text" class="form-control" name="location" id="location" value="{{ $event->location }}">
                    <input type="hidden" value="" id="distance" name="distance">
                    <input type="hidden" value="" id="time" name="time">
                    <div id="info-display"></div>
                </div>
                <div class="form-group">
                    <button type="button" class="btn btn-info" id="information">Check Distance and Time</button>
                </div>

                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
@endsection

resources/views/events/index.blade.php
@extends('base')
<div>
    <a style="margin: 19px;" href="{{ route('events.create')}}" class="btn btn-primary">New event</a>
</div>
@section('main')
    <div id="app" class="row">
        <div class="col-sm-12">
            @if(session()->get('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
            @endif
        </div>
        <div class="col-sm-12">
        <h1 class="display-3">Events</h1>
        <table id="grid" class="display" style="width:100%">
            <thead>
            <tr>
                <th>Name</th>
                <th>Event type</th>
                <th>Participants</th>
                <th>Organisers</th>
                <th>Event date</th>
                <th>Event time</th>
                <th>Venue</th>
                <th>Distance</th>
                <th>Duration</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($events as $event)
                <tr>
                    <td>{{$event['name']}}</td>
                    <td>{{$event['event_type']}}</td>
                    <td>{{$event['participants']}}</td>
                    <td>{{$event['organisers']}}</td>
                    <td>{{$event['date']}}</td>
                    <td>{{$event['time']}}</td>
                    <td>{{$event['location']}}</td>
                    @if(isset($event['venue_distance']))
                        <td>{{$event['venue_distance']."les"}}</td>
                    @else
                        <td>null</td>
                    @endif
                    @if(isset($event['venue_travel_time']))
                        <td>{{$event['venue_travel_time']}}</td>
                    @else
                        <td>null</td>
                    @endif
                    <td>
                        <a href="{{ route('events.edit',$event['event_id'])}}" >Edit</a>
                        <form id="destroy" action="{{ route('events.destroy', $event['event_id'])}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        </div>
    </div>
@endsection